nav_far_user:
    resource: "@NavFarUserBundle/Controller/"
    type:     annotation
    prefix:   /

nav_far_utility:
    resource: "@NavFarUtilityBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
