<?php

namespace NavFar\GameBundle\Repository;

/**
 * CategorizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorizeRepository extends \Doctrine\ORM\EntityRepository
{
}
