<?php

namespace NavFar\GameBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
  public function getLastComments($max=5){
    $em=$this->getEntityManager();
    $query=$em->createQuery('SELECT c FROM NavFarGameBundle:Comments c order by c.id DESC');
    return $query->getResult();
  }
}
